name: web-service

on:
  push:
  
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_REPO: globe
  
jobs:
  build_and_test:
    name: Web Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Go test
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Login to Docker Hub
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      
      - name: Docker build
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .

      - name: Docker push
        run: |
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
